In [1]:
import numpy as np                             # Load NumPy library

In [2]:
my_array = np.array([[1, 2, 3], [4, 5, 6]])    # Create example array
print(my_array)                                # Print example array

[[1 2 3]
 [4 5 6]]


In [3]:
print(np.sum(my_array))                        # Get sum of all array values

21


In [4]:
print(np.sum(my_array, axis = 0))              # Get sum of array columns

[5 7 9]


In [5]:
print(np.sum(my_array, axis = 1))              # Get sum of array rows

[ 6 15]


In [6]:
my_list = [8, 4, 4, 3, 2, 4, 1, 3, 5, 2, 1, 3, 7]             # Create example list
print(my_list)  

[8, 4, 4, 3, 2, 4, 1, 3, 5, 2, 1, 3, 7]


In [7]:
print(np.quantile(my_list, q = np.arange(0.25, 1, 0.25)))     # Get quartiles of list
# [2. 3. 4.]

[2. 3. 4.]


In [8]:
print(np.quantile(my_list, q = np.arange(0.1, 1, 0.1)))       # Get deciles of list
# [1.2 2.  2.6 3.  3.  4.  4.  4.6 6.6]

[1.2 2.  2.6 3.  3.  4.  4.  4.6 6.6]


In [9]:
print(np.quantile(my_list, q = np.arange(0.01, 1, 0.01)))     # Get percentiles of list

[1.   1.   1.   1.   1.   1.   1.   1.   1.08 1.2  1.32 1.44 1.56 1.68
 1.8  1.92 2.   2.   2.   2.   2.   2.   2.   2.   2.   2.12 2.24 2.36
 2.48 2.6  2.72 2.84 2.96 3.   3.   3.   3.   3.   3.   3.   3.   3.
 3.   3.   3.   3.   3.   3.   3.   3.   3.12 3.24 3.36 3.48 3.6  3.72
 3.84 3.96 4.   4.   4.   4.   4.   4.   4.   4.   4.   4.   4.   4.
 4.   4.   4.   4.   4.   4.12 4.24 4.36 4.48 4.6  4.72 4.84 4.96 5.16
 5.4  5.64 5.88 6.12 6.36 6.6  6.84 7.04 7.16 7.28 7.4  7.52 7.64 7.76
 7.88]
