In [1]:
my_list = [4, 1, 3, 8, 2, 7, 5, 8, 2, 7, 9, 1, 5]  # Create example list
print(my_list)                                     # Print example list

[4, 1, 3, 8, 2, 7, 5, 8, 2, 7, 9, 1, 5]


In [2]:
import statistics                                  # Import statistics

In [3]:
print(statistics.pstdev(my_list))                  # Apply pstdev() function

2.7218163096852512


In [4]:
print(statistics.stdev(my_list))                   # Apply stdev() function

2.8329562343320847


In [5]:
import numpy as np                       # Import NumPy library in Python

In [6]:
my_array = np.array([[1, 2, 7, 2, 3],    # Create example array
                     [7, 1, 1, 5, 6],
                     [5, 2, 5, 5, 8]])
print(my_array)                          # Print example array

[[1 2 7 2 3]
 [7 1 1 5 6]
 [5 2 5 5 8]]


In [7]:
print(np.std(my_array))                  # Get standard deviation of all array values

2.3380903889000244


In [8]:
print(np.std(my_array, ddof = 1))        # Get standard deviation of all array values

2.4201534780139164


In [9]:
print(np.std(my_array, axis = 0))        # Get standard deviation of array columns

[2.49443826 0.47140452 2.49443826 1.41421356 2.05480467]


In [10]:
print(np.std(my_array, axis = 1))        # Get standard deviation of array rows

[2.0976177  2.52982213 1.8973666 ]


In [11]:
my_list = [2, 7, 5, 5, 3, 9, 5, 9, 3, 1, 1]      # Create example list
print(my_list)                                   # Print example list

[2, 7, 5, 5, 3, 9, 5, 9, 3, 1, 1]


In [12]:
print(np.std(my_list))                           # Get standard deviation of list

2.7423823870906103


In [13]:
import pandas as pd      

In [14]:
data = pd.DataFrame({'x1':range(42, 11, - 2),    # Create pandas DataFrame
                     'x2':[5, 9, 7, 3, 1, 4, 5, 4, 1, 2, 3, 3, 8, 1, 7, 5],
                     'x3':range(200, 216),
                     'group':['A', 'C', 'B', 'C', 'B', 'B', 'C', 'A', 'C', 'A', 'C', 'A', 'B', 'C', 'B', 'B']})
print(data)                                      # Print pandas DataFrame

    x1  x2   x3 group
0   42   5  200     A
1   40   9  201     C
2   38   7  202     B
3   36   3  203     C
4   34   1  204     B
5   32   4  205     B
6   30   5  206     C
7   28   4  207     A
8   26   1  208     C
9   24   2  209     A
10  22   3  210     C
11  20   3  211     A
12  18   8  212     B
13  16   1  213     C
14  14   7  214     B
15  12   5  215     B


In [15]:
print(data['x1'].std())                          # Get standard deviation of one column
# 9.521904571390467

9.521904571390467


In [16]:
print(data.std())                                # Get standard deviation of all columns

x1    9.521905
x2    2.516611
x3    4.760952
dtype: float64


/var/folders/2c/19wbw1_d4pv7bl31_4pf2_xm0000gn/T/ipykernel_19512/749633502.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(data.std())                                # Get standard deviation of all columns


In [17]:
print(data.std(axis = 1))                        # Get standard deviation of rows

0     103.568013
1     103.074407
2     104.787086
3     107.220956
4     108.932701
5     108.868422
6     109.546033
7     110.924900
8     112.988200
9     113.694034
10    114.421735
11    115.494589
12    115.001449
13    118.306100
14    117.542900
15    119.274194
dtype: float64


/var/folders/2c/19wbw1_d4pv7bl31_4pf2_xm0000gn/T/ipykernel_19512/829683533.py:1: FutureWarning: Dropping of nuisance columns in DataFrame reductions (with 'numeric_only=None') is deprecated; in a future version this will raise TypeError.  Select only valid columns before calling the reduction.
  print(data.std(axis = 1))                        # Get standard deviation of rows


In [18]:
print(data.groupby('group').std())               # Get standard deviation by group

              x1        x2        x3
group                               
A       9.574271  1.290994  4.787136
B      11.290114  2.581989  5.645057
C       8.891944  3.011091  4.445972


In [19]:
data = pd.DataFrame({'x1':[5, 1, 5, 2, 1, 2, 9, 6, 9, 4, 7, 8],  # Create pandas DataFrame
                     'x2':range(51, 63),
                     'x3':range(10, 22),
                     'group1':['B', 'B', 'A', 'A', 'B', 'B', 'A', 'A', 'B', 'B', 'B', 'A'],
                     'group2':['a', 'a', 'a', 'a', 'a', 'a', 'b', 'b', 'b', 'b', 'b', 'b']})
print(data)  

    x1  x2  x3 group1 group2
0    5  51  10      B      a
1    1  52  11      B      a
2    5  53  12      A      a
3    2  54  13      A      a
4    1  55  14      B      a
5    2  56  15      B      a
6    9  57  16      A      b
7    6  58  17      A      b
8    9  59  18      B      b
9    4  60  19      B      b
10   7  61  20      B      b
11   8  62  21      A      b


In [20]:
print(data.groupby('group1').std())                  # Get standard deviation by group

              x1        x2        x3
group1                              
A       2.738613  3.563706  3.563706
B       3.078342  3.903600  3.903600


In [21]:
print(data.groupby(['group1', 'group2']).std())      # Get standard deviation by multiple groups

                     x1        x2        x3
group1 group2                              
A      a       2.121320  0.707107  0.707107
       b       1.527525  2.645751  2.645751
B      a       1.892969  2.380476  2.380476
       b       2.516611  1.000000  1.000000


In [22]:
data.to_csv('data.csv', index = False)      # Export pandas DataFrame to CSV